# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doxctl < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://www.github.com/slmingol/doxctl"
  version "0.0.30-alpha"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slmingol/doxctl/releases/download/0.0.30-alpha/doxctl_0.0.30-alpha_Darwin_x86_64.tar.gz"
      sha256 "15f1c9f7d7d0db103cedb337e0c66412ef261dc6d3d79f5d5010e89fdbd3d2fb"
    end

    depends_on arch: [:x86_64]
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/slmingol/doxctl/releases/download/0.0.30-alpha/doxctl_0.0.30-alpha_Linux_x86_64.tar.gz"
      sha256 "c0cbcfb2dadfccf497f9f82bcdd211db9105f19bf668a0052f4fc5cb97803980"
    end

    depends_on arch: [:x86_64]
  end

  depends_on "go"
  depends_on "coreutils"

  def install
    bin.install "doxctl"
  end

  test do
    system "#{bin}/doxctl"
  end
end
