# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gauth < Formula
  desc "Command line 2FA Authentication"
  homepage "https://www.github.com/slmingol/gauth"
  version "1.05"
  license "MIT"

  depends_on "go"
  depends_on "coreutils"

  on_macos do
    url "https://github.com/slmingol/gauth/releases/download/v1.05/gauth_1.05_Darwin_x86_64.tar.gz"
    sha256 "538f5ee494e17db0afc57379e0af9bf187d9d504fc6b0f66c9f8c34cf4e14a2d"

    def install
      bin.install "gauth"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Gauth
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/slmingol/gauth/releases/download/v1.05/gauth_1.05_Linux_x86_64.tar.gz"
      sha256 "398f26d21cfa215ce4a420916b97c791dfe948485ccb087560403b9fb9dc2c1c"

      def install
        bin.install "gauth"
      end
    end
  end

  test do
    system "#{bin}/gauth"
  end
end
