# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gauth < Formula
  desc "Command-line TOTP/2FA authenticator for terminal-based two-factor auth"
  homepage "https://github.com/slmingol/gauth"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/slmingol/gauth/releases/download/v1.6.1/gauth_1.6.1_Darwin_amd64.tar.gz"
      sha256 "9355641171f9450f978d5e724ebc511f80287122b1b9c30f50a5a9eb98f80845"
    end
    on_arm do
      url "https://github.com/slmingol/gauth/releases/download/v1.6.1/gauth_1.6.1_Darwin_arm64.tar.gz"
      sha256 "1de95ca241a1be3c6f5d1faf23962e3bc214c3dc57616cc56705c68b6e40f8be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/slmingol/gauth/releases/download/v1.6.1/gauth_1.6.1_Linux_amd64.tar.gz"
      sha256 "85302da94d801adf7c6da0f5b7b43da11d8f95c021b07f81be88e8ec80cb36b1"
    end
    on_arm do
      url "https://github.com/slmingol/gauth/releases/download/v1.6.1/gauth_1.6.1_Linux_arm64.tar.gz"
      sha256 "eb3475901b1e34f92356d4a5de42c7dde4f4ac69fc9211b0cfe0bb5feb48ff4d"
    end
  end

  def install
    bin.install "gauth"
  end

  test do
    assert_predicate bin/"gauth", :executable?
  end
end
