# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gauth < Formula
  desc "Command-line TOTP/2FA authenticator for terminal-based two-factor auth"
  homepage "https://github.com/slmingol/gauth"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/slmingol/gauth/releases/download/v1.06/gauth_1.06_Darwin_amd64.tar.gz"
      sha256 "866c7da304ce9d5a28b0c50ea4d6e4ce42d93fa2bb3ad191d53feac59af7cea0"
    end
    on_arm do
      url "https://github.com/slmingol/gauth/releases/download/v1.06/gauth_1.06_Darwin_arm64.tar.gz"
      sha256 "693da2d5a7e9fcb372debb4bea38006a959881b7ba90703b86e24554fd8c9514"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/slmingol/gauth/releases/download/v1.06/gauth_1.06_Linux_amd64.tar.gz"
      sha256 "47fe9e1c25416ecff15e47af34ace56ed3b694cca3cb72ed556e9fa454282175"
    end
    on_arm do
      url "https://github.com/slmingol/gauth/releases/download/v1.06/gauth_1.06_Linux_arm64.tar.gz"
      sha256 "574cf713973bd079e7598a257a0f4faa6fced213272eb8310a2bd895076c5ae2"
    end
  end

  def install
    bin.install "gauth"
  end

  test do
    assert_predicate bin/"gauth", :executable?
  end
end
