# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaseEx < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://www.github.com/slmingol/gorlease_ex"
  version "0.0.85"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/slmingol/gorelease_ex/releases/download/0.0.85/gorelease_ex_0.0.85_Darwin_x86_64.tar.gz"
    sha256 "253b000e765fe075ce14d47f63bc696f75d3456284b3fb10b24149fe72ac1ff1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/slmingol/gorelease_ex/releases/download/0.0.85/gorelease_ex_0.0.85_Linux_x86_64.tar.gz"
    sha256 "01025b0066eee6720aa6b0ef8a23c3bb6aaee1a85a0512438367a492d3e1ae92"
  end

  depends_on "go"
  depends_on "coreutils"

  def install
    bin.install "gorelease_ex"
  end

  test do
    system "#{bin}/gorelease_ex"
  end
end
