# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaseEx < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://www.github.com/slmingol/gorlease_ex"
  version "0.0.74"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/slmingol/gorelease_ex/releases/download/0.0.74/gorelease_ex_0.0.74_Darwin_x86_64.tar.gz"
    sha256 "5b99e49c446885b3c16f96e3fa5b8ea81d41b30dc60c3ea3a77c92051ebd0758"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/slmingol/gorelease_ex/releases/download/0.0.74/gorelease_ex_0.0.74_Linux_x86_64.tar.gz"
    sha256 "aea86c276a537e4f7de108dc4751653c300ac80ba945b56c9762ef8a83cf3bac"
  end

  depends_on "go"
  depends_on "coreutils"

  def install
    bin.install "gorelease_ex"
  end

  test do
    system "#{bin}/gorelease_ex"
  end
end
