# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotcping < Formula
  desc "Yet another tcping for golang."
  homepage "https://www.github.com/slmingol/gotcping"
  version "0.0.3-alpha"
  license "MIT"

  depends_on "go"
  depends_on "coreutils"

  on_macos do
    url "https://github.com/slmingol/gotcping/releases/download/0.0.3-alpha/gotcping_0.0.3-alpha_Darwin_x86_64.tar.gz"
    sha256 "3b71503afa8d6c013a702e8681961286d1565f63d2dfdca4346f8a3af5eedcab"

    def install
      bin.install "gotcping"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Gotcping
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/slmingol/gotcping/releases/download/0.0.3-alpha/gotcping_0.0.3-alpha_Linux_x86_64.tar.gz"
      sha256 "b975cdadb93e7e90154855f396a7dbf413bbddcad56c5fbce26d3c351187d7d8"

      def install
        bin.install "gotcping"
      end
    end
  end

  test do
    system "#{bin}/gotcping"
  end
end
